### ISSUE TITLE
LSP Client library

### ISSUE THREAD

**Issue by hanspr** [sourcegraph/go-lsp#4]
Hi Chris,

I'm Hans Peyrot, and I'm looking for a go client, or package to connect to LSP servers. I haven't found one yet.
Is this a project in that direction or just a snippet saved here?
Do you have an example of how I could use this code here to begin implementing one?
I'm aware of the gopls project but apparently that is the implementation of the server only, I do not see any implementation of a client there.

Thanks in advance for any help, Hans

**Comment by chrismwendt** [comment]
Hey Hans, I don't know of any client library written in Go (usually they're written in whichever language editor plugins require, e.g. JavaScript in VS Code).

**Comment by hanspr** [comment]
Thanks
